<?php

namespace AppBundle\Repository;

/**
 * PostsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostsRepository extends \Doctrine\ORM\EntityRepository
{
    public function getPostsByCategories($category, $limit = false)
    {
        $query = $this->createQueryBuilder('a')
            ->select('a')
            ->leftJoin('a.categories', 'c')
            ->addSelect('c');


        $query = $query->add('where', $query->expr()->in('c', ':c'))
            ->setParameter('c', $category);
        if ($limit) {
            $query->setMaxResults($limit);
        }
        $query->orderBy('a.dcr', 'DESC');
        return $query->getQuery()->getResult();

        return $query;

    }
}
