liip_imagine:
    resolvers:
       default:
          web_path:
              web_root: "%kernel.root_dir%/../web"
              cache_prefix: "media/cache"
    loaders:
        default:
            filesystem:
                data_root: "%kernel.root_dir%/../web"
    filter_sets:
        cache: ~
        category_page_une:
            quality: 100
            filters:
                upscale: { min: [730, 480] }
                thumbnail: { size: [730, 480], mode: outbound , format: png  }
        category_page_deux:
            quality: 100
            filters:
                upscale: { min: [255, 180] }
                thumbnail: { size: [255, 255], mode: outbound , format: png  }