liip_imagine:
    resolvers:
       default:
          web_path:
              web_root: "%kernel.root_dir%/../web"
              cache_prefix: "media/cache"

    filter_sets:
        cache: ~
        category_page_une:
            quality: 100
            filters:
                upscale: { min: [730, 480] }
                thumbnail: { size: [730, 480], mode: outbound , format: png  }
        category_page_deux:
            quality: 100
            filters:
                upscale: { min: [255, 180] }
                thumbnail: { size: [255, 255], mode: outbound , format: png  }
        730x320:
            quality: 100
            filters:
                upscale: { min: [730, 320] }
                thumbnail: { size: [730, 320], mode: outbound , format: png  }
        730x480:
            quality: 100
            filters:
                upscale: { min: [730, 480] }
                thumbnail: { size: [730, 480], mode: outbound , format: png  }
        540x355:
            quality: 100
            filters:
                upscale: { min: [540, 355] }
                thumbnail: { size: [540, 355], mode: outbound , format: png  }
        160x120:
            quality: 100
            filters:
                upscale: { min: [160, 120] }
                thumbnail: { size: [160, 120], mode: outbound , format: png  }
        350x350:
            quality: 100
            filters:
                upscale: { min: [350, 350] }
                thumbnail: { size: [350, 350], mode: outbound , format: png  }
        350x230:
            quality: 100
            filters:
                upscale: { min: [350, 230] }
                thumbnail: { size: [350, 230], mode: outbound , format: png  }
