sonata_admin:
    templates:
        #layout:               :Sonata:standard_layout.html.twig
        #dashboard:            :Core:dashboard.html.twig
    title:                'Cuisinez Avec Djouza'
    #title_logo:           public/logo.png

    templates:
        # default global templates
        layout:  ":sonata:standard_layout.html.twig"
sonata_block:
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin]