services:
    admin.posts:
        class: AppBundle\Admin\PostsAdmin
        arguments: [~, AppBundle\Entity\Posts, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Post" ,label: 'Recettes', icon:'<i class="fa fa-envelope"></i>' }
        calls:
            - [addChild, ['@admin.comments']]
            - [ setTemplate, ['edit', 'AppBundle:AdminPost:edit.html.twig']]

    admin.category:
        class: AppBundle\Admin\CategoriesAdmin
        arguments: [~, AppBundle\Entity\Categories, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Post" ,label: 'Catégories', icon:'<i class="fa fa-envelope"></i>' }
    admin.comments:
        class: AppBundle\Admin\CommentsAdmin
        arguments: [~, AppBundle\Entity\Comments, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Post" ,label: 'Commentaires', icon:'<i class="fa fa-envelope"></i>' }

    admin.videos:
        class: AppBundle\Admin\VideosAdmin
        arguments: [~, AppBundle\Entity\Videos, ~] #MailingBundle:CRUD
        tags:
            - { name: sonata.admin, manager_type: orm, group: "WebTv" ,label: 'Videos Youtube'}
        #calls:
        #    - [ setTemplate, [edit, AppBundle:Videos:edit.html.twig]]

    admin.channel:
        class: AppBundle\Admin\ChannelAdmin
        arguments: [~, AppBundle\Entity\Channel, ~] #MailingBundle:CRUD
        tags:
            - { name: sonata.admin, manager_type: orm, group: "WebTv" ,label: 'Channel Youtube'}